### ISSUE TITLE
hello! tanks for your work.can your share your dataset?

### ISSUE THREAD

**Issue by zh9369** [ghaiszaher/Foggy-CycleGAN#3]

**Comment by ghaiszaher** [comment]
Hey @zh9369! 
As mentioned in the dissertation, I used parts of already existing datasets:
* [Cityscapes](https://www.cityscapes-dataset.com/)
* [SFSU - Foggy Driving](https://people.ee.ethz.ch/~csakarid/SFSU_synthetic/)
* [Reside](https://sites.google.com/view/reside-dehaze-datasets/reside-v0)

I would not be able share the datasets publicly due to copyright reasons, but I would be glad to share the annotated datasets with you if you send me an email to ghaiszaher@gmail.com.

Bests!

**Comment by zkailinzhang** [comment]
Exception: No annotation files found!
